# things set by configure

_MAKE_VERSION?=20260704

prefix?= /tmp/slurabsd-obj/bmake-install
srcdir= /root/sluraproj/slurabsd/contrib/bmake
CC= gcc
MAKE_OS?= 
MACHINE?= amd64
MACHINE_ARCH?= x86_64
DEFAULT_SYS_PATH?= /tmp/slurabsd-obj/bmake-install/share/mk:/usr/share/mk
MAKE_SAVE_DOLLARS_DEFAULT?= no

EGREP = egrep
CPPFLAGS+= 
CFLAGS+= ${CPPFLAGS} -DHAVE_CONFIG_H
LDFLAGS+= 
LIBOBJS+=  ${LIBOBJDIR}stresep$U.o
LDADD+= 
USE_META?= yes
USE_FILEMON?= no
FILEMON_H?= 
BMAKE_PATH_MAX?= 1024
# used if MAXPATHLEN not defined
CPPFLAGS+= -DBMAKE_PATH_MAX=${BMAKE_PATH_MAX}
