[package]
name    = "vuc-types"
version = "0.0.1"
edition = { workspace = true }

[dependencies]
serde   = { workspace = true, default-features = false, features = ["derive"] }
base64  = { workspace = true, default-features = false }
bincode = { version = "2.0.1", features = ["derive", "std"] }

[lib]
name = "vuc_types"
path = "src/lib.rs"

[package.metadata]
license     = "Vylte-finuka"
description = "Vyft slurachain definitions and types."
